; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

lib_deps =
    # 1. Servo
    servo

    # 2. MPU-6050
    adafruit/Adafruit MPU6050

    # 3. TCA9548A TODO: non si sa se sia compatibile
    robtillaart/TCA9548

    # 4. Adafruit APDS9960
    adafruit/Adafruit APDS9960 Library

    # 5. Adafruit VL53L1X
    adafruit/Adafruit VL53L1X

    # Dipendenze
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor